[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "=0.3.26"
solana-sdk = "=1.10.29"
solana-client = "=1.10.29"
anchor-lang = "=0.25"
rand = "0.8.5"
libsodium-sys-stable = "=1.19.22"
serde = "=1.0.144"
serde_json = "=1.0.85"

program = { path = "../program" }